### ISSUE TITLE
attack_model.py does not seem to have transforms for Adult implemented

### ISSUE THREAD

**Issue by jctaillandier** [iPieter/ethical-adversaries#1]
Seems like when running on Adult Dataset, transformation (encoding) of dataset is trying to use the same as for German Credit (`transform_dataset_credit(df)`).
```
python3 -m pipenv run python main.py --epochs 50 --grl-lambda 50 --batch-size 128 --attack-size 10 --dataset adult --iterations 50 --save-dir ../results --show-graphs=False
(32561, 9)
Traceback (most recent call last):
  File "main.py", line 429, in <module>
    main(args)
  File "main.py", line 302, in main
    df_binary, Y, S, _ = transform_dataset_census(df)
  File "/home/jc-damballa/work/ethical-adversaries/scripts/attack_model.py", line 139, in transform_dataset_census
    encod_feature = df_replace.iloc[:,i]
  File "/home/jc-damballa/Devel/.virtualenvs/ethical-adversaries-aOfeZCpr/lib/python3.7/site-packages/pandas/core/indexing.py", line 1762, in __getitem__
    return self._getitem_tuple(key)
  File "/home/jc-damballa/Devel/.virtualenvs/ethical-adversaries-aOfeZCpr/lib/python3.7/site-packages/pandas/core/indexing.py", line 2067, in _getitem_tuple
    self._has_valid_tuple(tup)
  File "/home/jc-damballa/Devel/.virtualenvs/ethical-adversaries-aOfeZCpr/lib/python3.7/site-packages/pandas/core/indexing.py", line 703, in _has_valid_tuple
    self._validate_key(k, i)
  File "/home/jc-damballa/Devel/.virtualenvs/ethical-adversaries-aOfeZCpr/lib/python3.7/site-packages/pandas/core/indexing.py", line 1994, in _validate_key
    self._validate_integer(key, axis)
  File "/home/jc-damballa/Devel/.virtualenvs/ethical-adversaries-aOfeZCpr/lib/python3.7/site-packages/pandas/core/indexing.py", line 2063, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
```
Has it been implemented? Or should I force the use of another transform function in `attack_model.py` to make sure the encoding goes through ?

**Comment by jctaillandier** [comment]
Sorry mate, just figured out it was the right function meant to transform `Adult` Dataset. Error is at line 114 where you want to remove the NA's you just created from those `?` values. But the line
```
    df_replace.dropna(inplace=True, axis=1)
``` 
Actually removes columns with NA's. so just need to change to 
```
    df_replace.dropna(inplace=True, axis=0)
```
This results in other error downstream, will look into those as well, but pretty sure this ^ fix should be made!

**Comment by jctaillandier** [comment]
Okay got it running, and simply needed to reset indexes when concatenating dataframes as you encode each columns, otherwise x_tensor has more rows than y_tensor when back in `main.py`.

I implemented it in my fork in case you want it here's the link:
`https://github.com/jctaillandier/ethical-adversaries/commit/3a25e94aec0f52ee68a51e2e5b0e2807d7e29975`
